### ISSUE TITLE
Can we preserve source data?

### ISSUE THREAD

**Issue by andrewzhurov** [trashhalo/logseq-summarizer#4]
It looks like when the script is run source data is being substituted with a derived out of it summary, so we end up loosing source data.
I can't think of a case where this behaviour may be wanted.. although perhaps there is.

It seems to me more practical to preserve source data, perhaps by accreting subject of summarization with a derived out of it summary?
E.g., under a bullet point.
E.g., having one big summary under the subject item
```
* content A
** summary
*** <summary of content A and content AA>
** content AA
```

or having granular summaries under each nested item
```
* content A
** summary
*** <summary of content A>
** content AA
*** summary
**** <summary of content AA>
```

**Comment by andrewzhurov** [comment]
Perhaps there is no need for an intermediate `summary` item between subject and summary if it is possible to accrete `summary` itself with metadata that it is a summary.
```
* subject
** summary
*** <summary content>
```

I'm thinking with org-mode's :PROPERTIES: under an item which is a store of arbitrary data, it seems likely that logseq's data model allows for something similar.
In org-mode it would look like
```
* subject
** <summary content>
   :PROPERTIES:
   :NODE_TYPE_OR_SOMETHING: summary
   :END:
```
Then it can be rendered in a special way and accreted with more data as we wish.

**Comment by trashhalo** [comment]
This all makes sense to me. I wasn't quite sure how to best integrate the summary. Thanks for the suggestion. I'll try to incorporate it into version 0.0.4.
